version: '3.9'
services:
  app:
    build: .
    container_name: tms_app
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: translation_service
      DB_USERNAME: root
      DB_PASSWORD: secret
    command: sh -c "php artisan serve --host=0.0.0.0 --port=8000"
  db:
    image: mysql:8.0
    container_name: tms_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: translation_service
    ports:
      - "33060:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:

